version: "3.9"
services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    env_file:
      - .env
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASS} --save 60 1 --loglevel warning
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  exchanger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchanger
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: celery_app
    command: [ "/app/entrypoints/celery.sh" ]
    depends_on:
      - redis
      - db
      - exchanger
