version: "3.9"
services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
  exchanger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchanger
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
