"""initial

Revision ID: 0001
Revises: 
Create Date: 2024-01-16 17:13:18.186166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchanger', sa.String(), nullable=True),
    sa.Column('coin_from', sa.String(), nullable=True),
    sa.Column('coin_to', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rate_exchanger'), 'exchange_rate', ['exchanger'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rate_exchanger'), table_name='exchange_rate')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
